# Generated by Django 3.2.14 on 2022-11-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=300, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=200, null=True, verbose_name='Descripción')),
                ('prioridad', models.IntegerField(default=1, verbose_name='Prioridad')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('vigente', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do.proyecto')),
            ],
        ),
    ]
