# Generated by Django 3.2.14 on 2022-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Urgente e importante'), (2, 'Urgente'), (3, 'Importante'), (4, 'Ni urgente ni importante (Delegar)')], default=1),
        ),
    ]
