# Generated by Django 3.2.14 on 2022-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_auto_20221120_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(default=3, unique=True),
            preserve_default=False,
        ),
    ]
